CDdurumi/Final-project

pom.xml
<java-version>11</java-version>
<org.springframework-version>5.3.20</org.springframework-version>
=> pom.xml init

pom.xml
=> pom.xml init dependencies add

src/main/webapp/WEB-INF/web.xml
=> web.xml encoding filter

src/main/webapp/WEB-INF/spring/root-context.xml
=> root-context.xml init

src/main/webapp/WEB-INF/views/community/coummunityMain.jsp
=> coummunityMain.jsp add

src/main/java/kh/spring/Controller/CoummunityController.java, src/main/webapp/WEB-INF/views/community/communityMain.jsp
=> communityController create and communityMain.jsp modified

src/main/webapp/WEB-INF/views/common/footer.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/index.jsp
1. footer.jsp 기본 세팅 완료
2. 로고 이미지 미삽입
3. index.jsp / header.jsp fontawesome CDN 입력, footer.jsp 없음
=> footer.jsp 기본 완료

src/main/webapp/WEB-INF/views/community/communityMain.jsp, src/main/webapp/resources/css/communityMain.css
커뮤니티 메인 전용 css생성 및 커뮤니티 메인jsp 작업중
=> communityMain.css create and communityMain.jsp modified

src/main/webapp/WEB-INF/views/member/mypage.jsp, src/main/webapp/resources/css/mypage.css
1. mypage.jsp 생성 
2. mypage.css 생성
=> mypage.jsp & css created

pom.xml, src/main/java/kh/spring/Controller/SignUpController.java, src/main/java/kh/spring/Service/SignupService.java, src/main/resources/mybatis/signup-mapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
=> gmail auth

src/main/java/kh/spring/DAO/Class1DAO.java, src/main/java/kh/spring/DAO/Review1DAO.java, src/main/java/kh/spring/DTO/Review1DTO.java
files related to myPage all included
=> files related to myPage all included

src/main/webapp/WEB-INF/views/community/boardWrite.jsp
=> boardWrite text_length check

src/main/java/kh/spring/Controller/ServiceCenterController.java, src/main/java/utils/Pagination.java, src/main/webapp/WEB-INF/views/center/centerList.jsp, src/main/webapp/resources/css/center/centerList.css
=> 비동기 페이지네이션 구현

src/main/java/kh/spring/Controller/ServiceCenterController.java, src/main/java/kh/spring/DAO/ServiceCenterDAO.java, src/main/java/kh/spring/Service/CenterService.java, src/main/resources/mybatis/CS-mapper.xml, src/main/webapp/WEB-INF/views/center/noticeDetail.jsp, src/main/webapp/WEB-INF/views/center/noticeWrite.jsp, src/main/webapp/resources/css/center/inquiryDetail.css
오늘 중으로 자주묻는 질문 아코디언이랑, 1대1문의 완성할 예정입니다.
=> 고객센터 공지글 CRUD 완성

src/main/java/kh/spring/Controller/LoginController.java, src/main/java/kh/spring/DAO/LoginDAO.java, src/main/java/kh/spring/Service/LoginService.java, src/main/java/kh/spring/interceptor/LoginValidator.java, src/main/resources/mybatis/login-mapper.xml, src/main/webapp/WEB-INF/views/center/centerList.jsp, src/main/webapp/WEB-INF/views/center/noticeDetail.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/common/loginModal.jsp, src/main/webapp/WEB-INF/views/common/pNav.jsp, src/main/webapp/WEB-INF/views/index.jsp
=> 로그인 세션 문제 해결 및 아이디 기억하기 기능 구현

src/main/java/kh/spring/Controller/ServiceCenterController.java, src/main/java/kh/spring/DAO/ServiceCenterDAO.java, src/main/java/kh/spring/DTO/InquiryDTO.java, src/main/java/kh/spring/DTO/ReplyInquiryDTO.java, src/main/java/kh/spring/Service/CenterService.java, src/main/java/utils/Pagination.java, src/main/resources/mybatis/CS-mapper.xml, src/main/webapp/WEB-INF/views/center/centerList.jsp
ReviewDTO 없어서 서버 구동이 안되네요. 그래서 서버 안키고 일단 만들어봤습니다.
=> inquiry List

src/main/java/kh/spring/Controller/CoummunityController.java, src/main/java/kh/spring/Service/CommunityService.java, src/main/webapp/WEB-INF/views/community/detailView.jsp, src/main/webapp/resources/css/community/boardDetailView.css
커뮤니티 게시글 디테일뷰 공유기능, 본문 이미지 출력 완
=> detailView img output and share complete

src/main/java/kh/spring/Controller/LoginController.java, src/main/java/kh/spring/DAO/LoginDAO.java, src/main/java/kh/spring/DAO/SignupDAO.java, src/main/java/kh/spring/Service/LoginService.java, src/main/resources/mybatis/login-mapper.xml, src/main/resources/mybatis/signup-mapper.xml, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/common/loginModal.jsp, src/main/webapp/WEB-INF/views/common/signup.jsp, src/main/webapp/WEB-INF/views/common/snsdata.jsp, src/main/webapp/resources/css/login/snsdata.css
=> 카카오 로그인 API 완료

src/main/java/kh/spring/Controller/CoummunityController.java, src/main/java/kh/spring/DAO/CommunityDAO.java, src/main/java/kh/spring/DAO/ReplyDAO.java, src/main/java/kh/spring/Service/CommunityService.java, src/main/resources/mybatis/community-mapper.xml, src/main/resources/mybatis/good-mapper.xml, src/main/resources/mybatis/reply-mapper.xml, src/main/webapp/WEB-INF/views/community/detailView.jsp, src/main/webapp/resources/css/community/boardDetailView.css
=>  reply_delete complete

src/main/java/kh/spring/Controller/CoummunityController.java, src/main/java/kh/spring/DAO/ReplyDAO.java, src/main/java/kh/spring/Service/CommunityService.java, src/main/resources/mybatis/reply-mapper.xml, src/main/webapp/WEB-INF/views/community/detailView.jsp, src/main/webapp/resources/css/community/boardDetailView.css
=> reply modi complete

src/main/webapp/WEB-INF/views/community/boardModi.jsp, src/main/webapp/WEB-INF/views/community/boardWrite.jsp, src/main/webapp/WEB-INF/views/community/detailView.jsp
댓글, 대댓글 등록 및 수정 시 공백 입력 못하게, 길이 제한
=> detailView reg length limit

src/main/webapp/WEB-INF/views/community/detailView.jsp
=> 커뮤니티 디테일 뷰 마감하기 수정

src/main/webapp/WEB-INF/views/community/communityMain.jsp, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/resources/css/community/boardDetailView.css, src/main/webapp/resources/css/index.css
=> index community output complete

src/main/webapp/WEB-INF/views/community/detailView.jsp, src/main/webapp/resources/css/community/boardDetailView.css
=> detailView regBtn layout modified

src/main/java/kh/spring/Controller/CoummunityController.java, src/main/java/kh/spring/Service/CommunityService.java
글 작성 후 메인으로 이동에서 -> 글 작성 후 자신이 작성한 게시글 디테일 페이지로 전환되도록 수정
=>  communityController_writePro return logic modified

src/main/webapp/WEB-INF/views/community/communityMain.jsp, src/main/webapp/WEB-INF/views/community/detailView.jsp
커뮤니티 메인, 디테일 뷰 시간 만들어 주는 함수 수정
=> reg_date output function modified

src/main/java/kh/spring/Controller/MypageController.java, src/main/java/kh/spring/Service/MypageService.java, src/main/webapp/WEB-INF/views/member/myOpenClass.jsp, src/main/webapp/resources/css/member/myPage.css
1. 마이페이지에서 정보 수정 시 세션에 반영
2. 기타 잡다한 css 수정..
=> myOpenClass some chages & session renewal when change info

src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/resources/css/member/memberOut.css
마이페이지 프로필 사진 등록 시 파일 이미지 제한 코드 추가
=> mypage profile image file size limit function added

src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/resources/css/member/myPage.css
=> password change function blocked for kakao/google account

src/main/webapp/WEB-INF/views/member/myPage.jsp
=> admin member out function blocked

src/main/webapp/WEB-INF/views/center/inquiryDetail.jsp, src/main/webapp/WEB-INF/views/center/inquiryWrite.jsp, src/main/webapp/WEB-INF/views/center/noticeDetail.jsp, src/main/webapp/WEB-INF/views/center/noticeWrite.jsp, src/main/webapp/WEB-INF/views/common/loginModal.jsp
로컬에선 문제없는데 사이트에서는 약간의 차이가 있어 수정했습니다.
=> 구글 이미지 마진 조정

src/main/resources/mybatis/mypage-mapper.xml, src/main/webapp/WEB-INF/views/member/myOpenClass.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/resources/css/member/myPage.css
css & 로직 부분 디테일 잡고 완성도 높이는 중입니당
=> myPage about class modified

src/main/java/kh/spring/Service/MypageService.java, src/main/webapp/WEB-INF/views/member/changePw.jsp, src/main/webapp/WEB-INF/views/member/changePwNext.jsp, src/main/webapp/WEB-INF/views/member/changePwOk.jsp, src/main/webapp/WEB-INF/views/member/memberOut.jsp, src/main/webapp/WEB-INF/views/member/memberOutOk.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/resources/css/member/myPage.css
1. 프로필 사진 수정, 기본 이미지로 변경, 회원 탈퇴 시 서버 업로드 프로필 이미지 파일 삭제 로직 추가 (이걸 이제야 발견했다니..)
2. 테스트케이스 에러 조치 완료
3. 기타 css 관련 건의 반영 완료
=> myPage-testcase error fixed & css modified & server upload profile img delete logic added

src/main/webapp/WEB-INF/views/center/centerList.jsp, src/main/webapp/resources/css/center/centerList.css
=> cs center - FAQ modified

src/main/webapp/resources/css/index.css
인덱스 커뮤니티 부분 최신글 해쉬태그 2줄 이상 넘침 방지 처리 했습니다
=> index.css modified

src/main/webapp/WEB-INF/views/admin/adminMemberCommunity.jsp, src/main/webapp/WEB-INF/views/center/centerList.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp
=> mypage & cs & admin jsp modified

src/main/resources/mybatis/login-mapper.xml
=> login_type -> type

src/main/webapp/WEB-INF/views/center/inquiryDetail.jsp
=> admin can modify or delete inquiry

src/main/webapp/WEB-INF/views/member/myPage.jsp
=> mypage my community img src changed

src/main/resources/mybatis/mypage-mapper.xml, src/main/webapp/WEB-INF/views/member/myPage.jsp
=> mypage-mapper and jsp little change

src/main/java/kh/spring/Controller/MypageController.java, src/main/java/kh/spring/DAO/MypageDAO.java, src/main/resources/mybatis/mypage-mapper.xml, src/main/webapp/WEB-INF/views/member/myPage.jsp
=> myPage get my community picture logic changed

src/main/webapp/WEB-INF/views/common/signup.jsp
영상 찍다가 회원가입 버튼이 기존에 활성화되면 다시 올렸을 때도 활성화되는 문제 발견해서 해결했습니다.
=> 회원가입 초기화 안되는 문제 해결

src/main/java/kh/spring/interceptor/LoginValidator.java, src/main/webapp/WEB-INF/views/error2.jsp, src/main/webapp/WEB-INF/web.xml
HTTP 404, 500 에러는 인터셉터에서 처리 불가.
web.xml로 스프링에서 자체적으로 처리하도록 설정해야한다네요.
=> HTTP Error 처리
